### PR TITLE
Update README.md with latest versions

### PR DESCRIPTION
**Pull request by jsravn**

### CODE REVIEW

**Comment by alangibson01** [comment]
@jsravn Shouldn't we update the version numbers in `examples/feed-dns-deployment.yml` and `examples/feed-ingress-deployment.yml` as well?

**Comment by jsravn** [comment]
@alangibson01 Hmm yeah we could. But this is going to be painful to update all the time. Maybe we should just use latest.

**Comment by alangibson01** [comment]
@jsravn If we can do that, it's probably a good idea. Version history is still going to be recorded in the changelog, if someone wants to see it for reference.

**Comment by jsravn** [comment]
@alangibson01 I updated it everywhere. If it becomes too painful, let's switch to using latest in the examples, and a concrete version in the README.md.

**Pull request merged**
