### PR TITLE
Add route53 dependency

### PR DESCRIPTION
**Pull request by balooo**

### CODE REVIEW

**Comment by chbatey** [comment]
Where is the change to the vendors file?

**Comment by chbatey** [comment]
Also I think this should just be a commit in your PR that uses this dependency

**Comment by jsravn** [comment]
I think it's okay if this is its own PR, makes it easier to rebase the next PR if it's a lot of commits. I'm indifferent...

**Comment by jsravn** [comment]
I guess it's sort of pointless on its own :).

**Comment by chbatey** [comment]
Either or :)

**Pull request merged**
